// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_rooms.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChatRoom = `-- name: CreateChatRoom :one
INSERT INTO chat_rooms(id, customer_id, company_id, created_at, updated_at)
VALUES($1, $2, $3, $4, $5)
RETURNING id, customer_id, company_id, created_at, updated_at
`

type CreateChatRoomParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	CompanyID  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error) {
	row := q.db.QueryRowContext(ctx, createChatRoom,
		arg.ID,
		arg.CustomerID,
		arg.CompanyID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
