// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(id, chat_room_id, sender_id, content, sent_at)
VALUES($1, $2, $3, $4, $5)
RETURNING id, chat_room_id, sender_id, content, file_url, file_name, file_size, sent_at, is_read
`

type CreateMessageParams struct {
	ID         uuid.UUID
	ChatRoomID uuid.UUID
	SenderID   uuid.UUID
	Content    sql.NullString
	SentAt     sql.NullTime
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ChatRoomID,
		arg.SenderID,
		arg.Content,
		arg.SentAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatRoomID,
		&i.SenderID,
		&i.Content,
		&i.FileUrl,
		&i.FileName,
		&i.FileSize,
		&i.SentAt,
		&i.IsRead,
	)
	return i, err
}
