// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ChatRoom struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	CompanyID  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Company struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Address      string
	Description  sql.NullString
	Photourl     sql.NullString
	Username     sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Customer struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Country      string
	Description  sql.NullString
	Photourl     sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Message struct {
	ID         uuid.UUID
	ChatRoomID uuid.UUID
	SenderID   uuid.UUID
	Content    sql.NullString
	FileUrl    sql.NullString
	FileName   sql.NullString
	FileSize   sql.NullString
	SentAt     sql.NullTime
	IsRead     sql.NullBool
}
