// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', updated_at = Now()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, customer_id, company_id, escrow_id, total_amount, status, description, created_at, updated_at
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.EscrowID,
		&i.TotalAmount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeOrder = `-- name: CompleteOrder :one
UPDATE orders
SET status = 'completed', updated_at = Now()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, customer_id, company_id, escrow_id, total_amount, status, description, created_at, updated_at
`

func (q *Queries) CompleteOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, completeOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.EscrowID,
		&i.TotalAmount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(id, company_id, customer_id, escrow_id, total_amount, status, description, created_at, updated_at)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, customer_id, company_id, escrow_id, total_amount, status, description, created_at, updated_at
`

type CreateOrderParams struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	CustomerID  uuid.UUID
	EscrowID    uuid.NullUUID
	TotalAmount string
	Status      string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.CompanyID,
		arg.CustomerID,
		arg.EscrowID,
		arg.TotalAmount,
		arg.Status,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.EscrowID,
		&i.TotalAmount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, company_id, escrow_id, total_amount, status, description, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.EscrowID,
		&i.TotalAmount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paidOrder = `-- name: PaidOrder :one
UPDATE orders
SET status = 'paid', updated_at = Now()
WHERE id = $1 AND status = 'pending'
RETURNING id, customer_id, company_id, escrow_id, total_amount, status, description, created_at, updated_at
`

func (q *Queries) PaidOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, paidOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.EscrowID,
		&i.TotalAmount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refundOrder = `-- name: RefundOrder :one
UPDATE orders
SET status = 'refunded', updated_at = Now()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, customer_id, company_id, escrow_id, total_amount, status, description, created_at, updated_at
`

func (q *Queries) RefundOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, refundOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.EscrowID,
		&i.TotalAmount,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
